using EPiServer.Find.Api.Querying;
using EPiServer.Find.Api.Querying.Queries;
using EPiServer.Find.Tracing;
using System.Linq;
using System.Text.RegularExpressions;

namespace EPiServer.Find
{

    public static class QueryHelpers
    {

        public static readonly Regex SpaceTabsRegex = new Regex(@"/\\s+/", RegexOptions.Compiled);
        public static readonly Regex TermsAndQuotedTermsRegex = new Regex(@"([\w-&´'`]+)|([""][\s\w-&´'`]+[""])", RegexOptions.Compiled);

        // Return all terms and phrases in query
        public static string[] GetQueryPhrases(string query)
        {            
            // Replace double space, tabs with single whitespace and trim space on side
            string cleanedQuery = SpaceTabsRegex.Replace(query, " ").Trim();

            // Match single terms and quoted terms, allow -&´'` in terms, allow space between quotes and word.
            return TermsAndQuotedTermsRegex.Matches(cleanedQuery).Cast<Match>().Select(c => c.Value.Trim()).Except(new string[] { "AND", "OR", "NOT"}).Take(50).ToArray();
        }

        public static string UnescapeElasticSearchQuery(string s)
        {
            return s.Replace("\\", "");
        }

        public static string EscapeElasticSearchQuery(string s)
        {
            return s.Replace("-", "\\-");
        }     

        public static bool GetFirstQueryStringQuery(ISearchContext context, out MinShouldMatchQueryStringQuery currentMinShouldMatchQueryStringQuery, out BoolQuery currentBoolQuery)
        {
            IQuery currentQuery;

            // Check for existing bool query with possible queries within and get the first which would be the one generated by For()
            if (QueryHelpers.TryGetBoolQuery(context.RequestBody.Query, out currentBoolQuery))
            {
                currentQuery = currentBoolQuery.Should.FirstOrDefault();
            }
            else
            {
                currentQuery = context.RequestBody.Query;
            }

            // Try get MinShouldMatchQueryStringQuery 
            if (TryGetMinShouldMatchQueryStringQuery(currentQuery, out currentMinShouldMatchQueryStringQuery))
            {                   
                return true;
            }
            
            // Try get MultiFiledQueryStringQuery and convert to MinShouldMatchQueryString because this is what all features in Toolbox work with
            if (TryGetMultiFieldQueryStringQuery(currentQuery, out MultiFieldQueryStringQuery currentMultiFieldQueryStringQuery))
            {
                // Convert to MinShouldMatchQueryStringQuery
                currentMinShouldMatchQueryStringQuery = new MinShouldMatchQueryStringQuery(currentMultiFieldQueryStringQuery.Query);
                return true;
            }

            // Try get MultiFiledQueryStringQuery and convert to MinShouldMatchQueryString because this is what all features in Toolbox work with
            if (TryGetQueryStringQuery(currentQuery, out QueryStringQuery currentQueryStringQuery))
            {
                // Convert to MinShouldMatchQueryStringQuery
                currentMinShouldMatchQueryStringQuery = new MinShouldMatchQueryStringQuery(currentQueryStringQuery.Query);
                return true;
            }

            return false;
        }

        public static bool TryGetMinShouldMatchQueryStringQuery(IQuery query, out MinShouldMatchQueryStringQuery currentMinShouldMatchQueryStringQuery)
        {

            currentMinShouldMatchQueryStringQuery = query as MinShouldMatchQueryStringQuery;
            if (currentMinShouldMatchQueryStringQuery == null)
            {
                return false;
            }
            return true;

        }

        public static bool TryGetMultiFieldQueryStringQuery(IQuery query, out MultiFieldQueryStringQuery currentMinShouldMatchQueryStringQuery) {

            currentMinShouldMatchQueryStringQuery = query as MinShouldMatchQueryStringQuery;
            if (currentMinShouldMatchQueryStringQuery == null)
            {
                return false;
            }
            return true;

        }

        public static bool TryGetQueryStringQuery(IQuery query, out QueryStringQuery currentQueryStringQuery)
        {

            currentQueryStringQuery = query as QueryStringQuery;
            if (currentQueryStringQuery == null)
            {
                return false;
            }            
            return true;

        }

        public static bool TryGetBoolQuery(IQuery query, out BoolQuery currentBoolQuery)
        {
            currentBoolQuery = query as BoolQuery;
            if (currentBoolQuery == null)
            {
                currentBoolQuery = new BoolQuery();
                return false;
            }

            return true;

        }

        /// <summary>
        /// Get query, default operator, analyzer and fields from current queryStringQuery (produced by For())
        /// </summary>
        /// <param name="currentQueryStringQuery"></param>
        /// <returns></returns>
        public static string GetQueryString(MultiFieldQueryStringQuery currentQueryStringQuery)
        {
            return (currentQueryStringQuery.Query.ToString().Trim() ?? string.Empty).ToString();
        }

        public static string GetRawQueryString(MultiFieldQueryStringQuery currentQueryStringQuery)
        {
            return (currentQueryStringQuery.RawQuery ?? string.Empty).Trim().ToString();
        }
        public static bool IsStringQuoted(string text)
        {
            return (text.StartsWith("\"") && text.EndsWith("\""));
        }
    }

}